site_name: log
site_description: Minimalistic wrapper for Python logging.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/minilog

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
