site_name: minilog
site_description: Minimalistic wrapper for Python logging.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/minilog
edit_uri: https://github.com/jacebrowning/minilog/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Logging: logging.md
  - Options: options.md
  - About:
      - Release Notes: about/changelog.md
      - Contributor Guide: about/contributing.md
      - License: about/license.md
