site_name: minilog
site_description: Minimalistic wrapper for Python logging.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/minilog
edit_uri: https://github.com/jacebrowning/minilog/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
- Home: index.md
- Logging: logging.md
- Extras: extras.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
